---
title: 'VU 2021 Election Study: Misinformatie Twitter'
author: "Mariken van der Velden & Andreu Casas"
permalink: reports/sm-propaganda/
output: 
  md_document:
    toc: yes
    preserve_yaml: yes
---

```{r setup, include=FALSE}
## include this at top of your RMarkdown file for pretty output
## make sure to have the printr package installed: install.packages('printr')
rm(list = ls())
knitr::opts_chunk$set(message = FALSE, warning = FALSE, 
                      echo = FALSE, fig.align = "center",
                        fig.path='')
library(glue)
library(printr)
options(digits = 2)
library(here)
library(tidyverse)
library(quanteda)
library(patchwork)
library(viridis)
source(here("src/lib/data.R"))
```

```{r "load data"}
d <- read_csv("../../../../../../Desktop/party-candidates-15aug2020-22feb2021.csv") %>% filter(day>"2021-01-15")

corp <- corpus(d, text_field = "text", meta = c("twitter"))
```

# Verspreiden van Informatie
In onderstaande figuur is te zien welke woorden Mark Rutte (zowel persoonlijk als ambtsaccount), Wopke Hoekstra, Gert-Jan Segers en Sigrid Kaag sinds het begin van de verkiezingscampagne het meest voorkomen. 
Hoe groter de woorden, hoe vaker 
Duidelijk wordt dat op basis van deze woorden er 

```{r "sharing on twitter - coalitiepartijen", fig.height=15, fig.width=10, fig.cap="Regeringspartijleiders op Twitter"}
dtm <- dfm(corp,
           remove = stopwords("Dutch"), remove_punct = TRUE, 
           groups = "twitter") %>%
    dfm_trim(min_termfreq = 3)

p1 <- textstat_frequency(dtm, groups = "twitter") %>%
  filter(frequency>5,
         group == "markrutte" | group ==  "MinPres") %>%
  ggplot(aes(x = frequency, y = feature)) +
  geom_col(fill = "#21908CFF") +
  facet_grid(group~., scales = "free", space = "free") +
  theme_minimal() +
  labs(y = "", 
       x = "",
       title = "Meest Gebruikte Woorden") + 
  theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          legend.position="none",
          legend.title = element_blank())

p2 <- textstat_frequency(dtm, groups = "twitter") %>%
  filter(frequency>5, group =="WBHoekstra" | group =="gertjansegers" | group =="SigridKaag") %>%
  ggplot(aes(x = frequency, y = feature)) +
  geom_col(fill = "#21908CFF") +
  facet_grid(group~., scales = "free", space = "free") +
  theme_minimal() +
  labs(y = "", 
       x = "") + 
  theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          legend.position="none",
          legend.title = element_blank())  

p1 + p2
```


```{r "sharing on twitter - oppositiepartijen", fig.height=15, fig.width=10, fig.cap="Regeringspartijleiders op Twitter"}
p3 <- textstat_frequency(dtm, groups = "twitter") %>%
  filter(frequency>5,
         group == "F_azarkan" | group =="jesseklaver" | group =="MarijnissenL" ) %>%
  ggplot(aes(x = frequency, y = feature)) +
  geom_col(fill = "#21908CFF") +
  facet_grid(group~., scales = "free", space = "free") +
  theme_minimal() +
  labs(y = "", 
       x = "",
       title = "Meest Gebruikte Woorden") + 
  theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          legend.position="none",
          legend.title = element_blank())

p4 <- textstat_frequency(dtm, groups = "twitter") %>%
  filter(frequency>5,
         group =="estherouwehand"| group =="keesvdstaaij" | group =="LianedenHaan" ) %>%
  ggplot(aes(x = frequency, y = feature)) +
  geom_col(fill = "#21908CFF") +
  facet_grid(group~., scales = "free", space = "free") +
  theme_minimal() +
  labs(y = "", 
       x = "",
       title = "Meest Gebruikte Woorden") + 
  theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          legend.position="none",
          legend.title = element_blank())
  
p5 <- textstat_frequency(dtm, groups = "twitter") %>%
  filter(frequency>5,
         group =="PloumenLilianne"| group =="geertwilderspvv") %>%
  ggplot(aes(x = frequency, y = feature)) +
  geom_col(fill = "#21908CFF") +
  facet_grid(group~., scales = "free", space = "free") +
  theme_minimal() +
  labs(y = "", 
       x = "",
       title = "Meest Gebruikte Woorden") + 
  theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          legend.position="none",
          legend.title = element_blank())

p6 <- textstat_frequency(dtm, groups = "twitter") %>%
  filter(frequency>15, group ==  "thierrybaudet") %>%
  ggplot(aes(x = frequency, y = feature)) +
  geom_col(fill = "#21908CFF") +
  facet_grid(group~., scales = "free", space = "free") +
  theme_minimal() +
  labs(y = "", 
       x = "",
       title = "Meest Gebruikte Woorden") + 
  theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          legend.position="none",
          legend.title = element_blank())

p3 + p4 + p5 + p6 + plot_layout(ncol=2)
```

```{r}

k <- kwic(corp, '#*', window = 7)
k_dtm <- dfm(k$keyword)
textplot_wordcloud(k_dtm, min_count = 5, color = )
```
